services:
  redis:
    image: redis:7.4.1
    ports:
      - "6379:6379"
    volumes:
      - ./redis/data:/data
    command: redis-server --appendonly yes

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - ./mongo/db:/data/db
    environment:
      TZ: Asia/Shanghai
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: 123456
  
#  kafka:
#    image: bitnami/kafka:3.8.0
#    ports:
#      - "9092:9092"
#    volumes:
#      - ./kafka:/bitnami/kafka
#    environment:
#      TZ: Asia/Shanghai
#      KAFKA_CFG_NODE_ID: 0
#      KAFKA_CFG_PROCESS_ROLES: controller,broker
#      KAFKA_CFG_CONTROLLER_QUORUM_VOTERS: 0@kafka:9093
#      KAFKA_CFG_LISTENERS: PLAINTEXT://:9092,CONTROLLER://:9093
#      KAFKA_CFG_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
#      KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
#      KAFKA_CFG_CONTROLLER_LISTENER_NAMES: CONTROLLER

  etcd:
    image: bitnami/etcd:3.5.16  
    ports:
      - "2379:2379"              
    environment:
      TZ: Asia/Shanghai
      ALLOW_NONE_AUTHENTICATION: yes
      ETCD_ADVERTISE_CLIENT_URLS: http://etcd:2379
    volumes:
      - ./etcd:/bitnami/etcd 
  
  etcdkeeper:
    image: deltaprojects/etcdkeeper:latest
    environment:
      TZ: Asia/Shanghai
    ports:
      - "8088:8080"
    depends_on:
      - etcd